### ISSUE TITLE
Ligand preparation failure for Schrodinger and Vina

### ISSUE THREAD

**Issue by MKCarter** [MolecularAI/DockStreamCommunity#5]
Hi,

I am trying to run the Glide and ADV demos. However, when I come to run the config via DockStream I am running into these types of errors for both Vina and Glide:

Vina Error:
```
Traceback (most recent call last):
  File "/Users/michaelcarter/DD_tools/DockStream/docker.py", line 127, in <module>
    ligand_number_start=0)
  File "/Users/michaelcarter/DD_tools/DockStream/dockstream/utils/entry_point_functions/embedding.py", line 38, in embed_ligands
    prep = CorinaLigandPreparator(ligands=list_ligands, pool_number=pool_number, **pool)
  File "/Users/michaelcarter/DD_tools/DockStream/dockstream/core/Corina/Corina_ligand_preparator.py", line 59, in __init__
    raise LigandPreparationFailed("Cannot initialize Corina backend - abort.")
dockstream.utils.dockstream_exceptions.LigandPreparationFailed: Cannot initialize Corina backend - abort.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/michaelcarter/DD_tools/DockStream/docker.py", line 132, in <module>
    raise LigandPreparationFailed
dockstream.utils.dockstream_exceptions.LigandPreparationFailed
```

Glide Error:

```
Traceback (most recent call last):
  File "/Users/michaelcarter/DD_tools/DockStream/docker.py", line 127, in <module>
    ligand_number_start=0)
  File "/Users/michaelcarter/DD_tools/DockStream/dockstream/utils/entry_point_functions/embedding.py", line 40, in embed_ligands
    prep = LigprepLigandPreparator(ligands=list_ligands, pool_number=pool_number, **pool)
  File "/Users/michaelcarter/DD_tools/DockStream/dockstream/core/Schrodinger/Ligprep_ligand_preparator.py", line 108, in __init__
    raise LigandPreparationFailed("Cannot initialize Ligprep backend - abort.")
dockstream.utils.dockstream_exceptions.LigandPreparationFailed: Cannot initialize Ligprep backend - abort.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/michaelcarter/DD_tools/DockStream/docker.py", line 132, in <module>
    raise LigandPreparationFailed
dockstream.utils.dockstream_exceptions.LigandPreparationFailed
```

Do you know of any solution to get this working?

Cheers,
Mike

**Comment by MKCarter** [comment]
To give a bit more context - this is the json code I am using to point to my Schrodinger installation:

```
# specify the embedding and docking JSON file as a dictionary and write it out
ed_dict = {
  "docking": {
    "header": {                                   # general settings
      "environment": {
      }
    },
    "ligand_preparation": {                       # the ligand preparation part, defines how to build the pool
      "embedding_pools": [
        {
          "pool_id": "Ligprep_pool",
          "type": "Ligprep",
          "parameters": {
            "prefix_execution": "export SCHRODINGER=/opt/schrodinger/suites2022-3",
            "parallelization": {
                "number_cores": 2
            },
            "use_epik": {
              "target_pH": 7.0,
              "pH_tolerance": 2.0
            },
            "force_field": "OPLS3e"
          },
          "input": {
            "standardize_smiles": False,
            "input_path": smiles_path,
            "type": "smi"                                   # expected input is a text file with smiles
          },
          "output": {                                       # the conformers can be written to a file, but "output" is
                                                            # not required as the ligands are forwarded internally
            "conformer_path": ligands_conformers_path, 
            "format": "sdf"
          }
        }
      ]
    },
    "docking_runs": [
        {
          "backend": "Glide",
          "run_id": "Glide_run",
        "input_pools": ["Ligprep_pool"],
        "parameters": {
          "prefix_execution": "export SCHRODINGER=/opt/schrodinger/suites2022-3", # will be executed before a program call
          "parallelization": {                              # if present, the number of cores to be used
                                                            # can be specified
            "number_cores": 2
          },
          "glide_flags": {                                  # all all command-line flags for Glide here 
            "-HOST": "localhost"
          },
          "glide_keywords": {                               # add all keywords for the "input.in" file here
            "AMIDE_MODE": "trans",
            "EXPANDED_SAMPLING": "True",
            "GRIDFILE": grid_file_path,
            "NENHANCED_SAMPLING": "2",
            "POSE_OUTTYPE": "ligandlib_sd",
            "POSES_PER_LIG": "3",
            "POSTDOCK_NPOSE": "15",
            "POSTDOCKSTRAIN": "True",
            "PRECISION": "HTVS",
            "REWARD_INTRA_HBONDS": "True"
          }
        },
        "output": {
          "poses": { "poses_path": ligands_docked_path },
          "scores": { "scores_path": ligands_scores_path }
        }
      }]}}

with open(docking_path, 'w') as f:
    json.dump(ed_dict, f, indent=2)
```

Do I have to also point towards my valid license for Maestro also?
